<?php

namespace frontend\controllers\api;

use common\helpers\ApiHandler;
use common\models\People;
use common\models\PeopleRoleType;
use yii\base\Exception;

class ClientController extends MasterController {

    public function actionInfo($idpeople) {
        try {
            $results = People::find()
                    ->joinWith(['peopleRole'])
                    ->where([
                        'idpeople' => $idpeople,
                        'idpeople_role_type' => PeopleRoleType::CLIENT,
                        'people.status' => 1,
                        'people_role.status' => 1,
                    ])
                    ->asArray()
                    ->all();

            ApiHandler::custom([
                'success' => true,
                'count' => count($results),
                'data' => $results,
            ]);
        } catch (Exception $e) {
            ApiHandler::failure($e->getMessage());
        }
    }

    public function beforeAction($action) {
//        if ($action->id == 'public-list')
            $this->public = FALSE;
//
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionPublicList() {
//        try {
//            $page = Yii::$app->request->get('page', 0);
//            $pageSize = SystemVar::getVar('news_listing_page_size');
//
//            $newses = News::find()
//                    ->select([
//                        News::tableName() . '.id',
//                        'title_' . $this->lang . ' as title',
//                        'cat_id',
//                        new Expression("DATE_FORMAT(FROM_UNIXTIME(" . News::tableName() . ".created_at), '%Y-%m-%d') as created_at")
//                    ])
//                    ->joinWith([
//                        'cat' => function ($query) {
//                            return $query->select([
//                                        'id',
//                                        $this->lang . ' as name'
//                            ]);
//                        },
//                        'thumbnail' => function ($query) {
//                            return $query
//                                    ->select(['thumbnail.model_id', Attachment::getDisplayUrl('thumbnail', 'url')])
//                                    ->onCondition(['thumbnail.field' => 'thumbnail_' . $this->lang]);
//                        },
//                    ])
//                    ->where([
//                        'status' => News::STATUS_ACTIVE,
//                        'access_right' => 0
//                    ])
//                    ->andWhere(['IS NOT', 'title_' . $this->lang, NULL])
//                    ->andWhere(['between', new Expression('NOW()'), new Expression('start_datetime'), new Expression('end_datetime')])
//                    ->orderBy([
//                        'order' => SORT_ASC,
//                        News::tableName() . '.id' => SORT_DESC
//                    ])
//                    ->limit($this->getLimit($page, $pageSize))
//                    ->offset($this->getOffset($page, $pageSize))
//                    ->asArray()
//                    ->all();
//
//            ApiHandler::success($newses);
//        } catch (Exception $e) {
//            ApiHandler::failure($e->getMessage());
//        }
    }

    public function actionView() {
//        try {
//            $id = Yii::$app->request->get('id', 1);
//
//            $membership = $this->getMembership();
//
//            /** @var News $news */
//            $news = News::find()
//                    ->select([
//                        News::tableName() . '.id',
//                        'title_' . $this->lang . ' as title',
//                        'content_' . $this->lang . ' as content',
//                        'cat_id'
//                    ])
//                    ->joinWith([
//                        'cat' => function ($query) {
//                            return $query->select([
//                                        'id',
//                                        $this->lang . ' as name'
//                            ]);
//                        },
//                        'topImage' => function ($query) {
//                            return $query
//                                    ->select(['top_image.model_id', Attachment::getDisplayUrl('top_image', 'url')])
//                                    ->onCondition(['top_image.field' => 'top_image_' . $this->lang]);
//                        },
//                    ])
//                    ->where([
//                        'status' => News::STATUS_ACTIVE,
//                        News::tableName() . '.id' => $id
//                    ])
//                    ->andWhere(['<=', 'access_right', $membership['right']])
//                    ->andWhere(['between', new Expression('NOW()'), new Expression('start_datetime'), new Expression('end_datetime')])
//                    ->asArray()
//                    ->one();
//
//            if ($news == NULL)
//                throw new Exception(WebLang::getTranslatedById(WebLang::RECORD_NOT_FOUND, $this->lang));
//
//            $_news = News::findOne($id);
//            $_news->hit_rate += 1;
//            $_news->save();
//
//            ApiHandler::success($news);
//        } catch (Exception $e) {
//            ApiHandler::failure($e->getMessage());
//        }
    }

}
